-- ==============================================================================
-- 迁移脚本: 为 school 库所有业务表添加多租户与主体隔离字段
-- 执行日期: 2026-08-30
-- ==============================================================================

USE `school`;

-- 1. 班级表 clazz
ALTER TABLE `clazz` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 2. 课程表 course
ALTER TABLE `course` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 3. 排课日程表 course_schedule
ALTER TABLE `course_schedule` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 4. 教学大纲表 course_syllabus
ALTER TABLE `course_syllabus` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 5. 学生表 student
ALTER TABLE `student` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 6. 学生荣誉表彰表 student_award
ALTER TABLE `student_award` 
  ADD COLUMN IF NOT EXISTS `level` VARCHAR(50) NOT NULL DEFAULT '院系级' COMMENT '荣誉级别' AFTER `award_name`,
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 7. 学生选课成绩表 student_course
ALTER TABLE `student_course` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 8. 学生隐私档案表 student_profile
ALTER TABLE `student_profile` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';

-- 9. 教师表 teacher
ALTER TABLE `teacher` 
  ADD COLUMN IF NOT EXISTS `project_no` VARCHAR(64) NOT NULL DEFAULT 'school' COMMENT '项目编号' AFTER `id`,
  ADD COLUMN IF NOT EXISTS `subject_id` BIGINT NOT NULL DEFAULT 1 COMMENT '主体ID' AFTER `project_no`,
  ADD COLUMN IF NOT EXISTS `created_by` BIGINT NULL COMMENT '创建人',
  ADD COLUMN IF NOT EXISTS `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ADD COLUMN IF NOT EXISTS `updated_by` BIGINT NULL COMMENT '更新人',
  ADD COLUMN IF NOT EXISTS `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN IF NOT EXISTS `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志: 0正常 1已删除';
